### ISSUE TITLE
Broken 'space dark' theme

### ISSUE THREAD

**Issue by palexdev** [aliakbarmostafaei/jetbrains-space-theme#9]
**Describe the bug**
Latest update seems to have broken 'Space Dark' theme, which now looks like this: 
![image](https://github.com/aliakbarmostafaei/jetbrains-space-theme/assets/16880178/578d3798-e07f-4638-97eb-ec0df02fc122)

**Expected behavior**
The editor should not be white on a dark theme preset

**Additional Info**
- OS: Windows 11
- Plugin version: 1.0.231012
- IntelliJ IDEA version: 2023.3 EAP (latest EAP, not tested on stable)

**Comment by aliakbarmostafaei** [comment]
I'm unable to reproduce this on IntelliJ IDEA 2033 EAP:

![Screenshot from 2023-10-12 19-19-49](https://github.com/aliakbarmostafaei/jetbrains-space-theme/assets/103068330/e9239d7a-cf6d-4c70-857d-c124dce1192f)

Although I noticed menu items are colored inconsistently on the latest EAP and it is patched now, you can grab the latest build from the releases section [v1.0.20231012.1](https://github.com/aliakbarmostafaei/jetbrains-space-theme/releases/tag/v1.0.20231012.1).

Your theme configurations may be corrupt, can you reset color schemes following this path:
`Settings -> Editor -> Color Schemes -> Select 'Space ...' -> Select 'Restore Defaults' clicking on the cogwheel`
Do this for all 'Space' color schemes, although you will lose any customization you have made to them so make sure to export a backup before doing so!
![Screenshot from 2023-10-12 19-44-53](https://github.com/aliakbarmostafaei/jetbrains-space-theme/assets/103068330/5cab4771-4577-4bbd-9e45-b937eb374c37)

Then select and re-apply the theme, if this doesn't resolve the issue, remove the plugin and re-install the binary from the releases page mentioned above and report back.

**Comment by palexdev** [comment]
Thank you very much for the rapid response!
I can confirm that the preview release fixes the menus:
![image](https://github.com/aliakbarmostafaei/jetbrains-space-theme/assets/16880178/f634d7fe-6e45-49d2-9a6e-d35287dae5cd)

I changed place and PC and at first I could not reproduce it. But then it happened again when switching to the 'Space Grey' variant. What I noticed though was that in the 'Color Scheme' settings, the scheme was set to 'Classical Light'!
I think that is a bug of IntelliJ

**Comment by aliakbarmostafaei** [comment]
You're welcome! Thanks for reporting!
Yes it is indeed a bug of IntelliJ tracked here at [IDEA-334062](https://youtrack.jetbrains.com/issue/IDEA-334062/Classic-Light-color-scheme-assigned-to-a-theme-gets-reset-after-switching-themes).
Expect to receive the update on JetBrains Plugin Marketplace within 2 business days.

**Comment by palexdev** [comment]
@aliakbarmostafaei thank you very much

Sorry to contact you here but I wanted to ask you if you are open to proposals on changes/improvements
Eventually I could try making a PR, though I'd first have to understand how it works

**Comment by aliakbarmostafaei** [comment]
> Sorry to contact you here but I wanted to ask you if you are open to proposals on changes/improvements Eventually I could try making a PR, though I'd first have to understand how it works

Yes, go ahead and create a new issue with your proposals and we'll discuss them. I'm more open to changes in the color schemes, I believe the overall UI colors are fine but who knows there's always room for improvement. PRs are also welcome.

**Comment by aliakbarmostafaei** [comment]
"Discussions" are now enabled on the repository.
